product_name: Upsource
product_version: 1.0

# It's a shame we can't change the location of _includes via config
plugins: _jekyll/_plugins
layouts: _jekyll/_layouts

markdown: kramdown
markdown_ext: md
kramdown:
  input: GFM2
  hard_wrap: false
  auto_ids: false
highlighter: pygments

exclude:
  - '*.scss'
  - '.build.cmd'
  - Vagrantfile*
  - Rakefile
  - lib
  - webhelp-template

defaults:
  - values:
      layout: 'webhelp'
