product_name: Upsource
product_version: 1.0

# It's a shame we can't change the location of _includes via config
plugins: _jekyll/_plugins
layouts: _jekyll/_layouts

# This is messy. This is also defined in _layouts/webhelp.html, but with a different value
# The webhelp.html 'baseurl' variable is prepended to the links in the files, e.g.
# {{baseurl}}/app/styles/... If this is '/', then it becomes //app/styles, and that looks
# like a hostname. If 'baseurl' is '', all is good. But the URLs from the tree view are
# prepended with the value of the data-baseurl attribute in the _includes/page.html template.
# This can't be '', or folders don't work. But fortunately, the template sets it to 'site.baseurl'
# and not 'baseurl', so we can cheat. Ideally, the 'baseurl' value wouldn't be used at all,
# and 'site.baseurl' would always be used, but assumed to have a trailing slash
baseurl: /

markdown: CustomKramdownParser

# Tell kramdown to the use the GFM2 parser so that it will parse GFM
# Tell the kramdown markdown processor to use the GFM2 parser. This derives from kramdown's
# GFM parser (which extends the default kramdown parser with GFM code fence support) to add
# support for highlighting a line, e.g. ```csharp{1 23}
kramdown:
  input: GFM2
  hard_wrap: false
  auto_ids: false
highlighter: pygments

exclude:
  - '*.scss'
  - '.build.cmd'
  - Vagrantfile*
  - Rakefile
  - lib
  - webhelp-template

defaults:
  - values:
      layout: 'webhelp'
